data = read.csv("output/data.csv")
regnw = lm(time~(f1+f2+f3+f4+f5+f6),data=data)
summary(regnw)
write.csv(coef(summary( regnw )), file= "output/r_files/outputresultReg.csv")
write.csv(anova(regnw), file= "output/r_files/ANOVA.csv") 